name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip

    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Download filey.zip
      run: Invoke-WebRequest -Uri "https://archive.org/download/filey/filey.zip" -OutFile filey.zip

    - name: Extract filey.zip
      run: Expand-Archive filey.zip -DestinationPath Setup

    - name: Install SendBlaster
      run: |
        $installerPath = Join-Path $env:GITHUB_WORKSPACE "Setup\SendBlaster Pro Edition v4.4.2.exe"
        Start-Process -FilePath "$installerPath" -ArgumentList '/silent /install' -Wait

    - name: Create ngrok Tunnel for RDP
      run: .\ngrok\ngrok.exe tcp 3389
